-- =====================================================
-- MySQL版本 - TPC-H表结构定义
-- 文件: 02_create_tables.sql
-- 功能: 创建TPC-H标准数据仓库表结构
-- =====================================================

USE TPC_H;

-- 创建REGION表（地区表）
DROP TABLE IF EXISTS REGION;
CREATE TABLE REGION (
    R_REGIONKEY INT PRIMARY KEY,
    R_NAME CHAR(25),
    R_COMMENT VARCHAR(152)
) ENGINE=InnoDB;

-- 创建NATION表（国家表）
DROP TABLE IF EXISTS NATION;
CREATE TABLE NATION (
    N_NATIONKEY INT PRIMARY KEY,
    N_NAME CHAR(25),
    N_REGIONKEY INT,
    N_COMMENT VARCHAR(152),
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
) ENGINE=InnoDB;

-- 创建PART表（零件表）
DROP TABLE IF EXISTS PART;
CREATE TABLE PART (
    P_PARTKEY INT PRIMARY KEY,
    P_NAME VARCHAR(55),
    P_MFGR CHAR(25),
    P_BRAND CHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE INT,
    P_CONTAINER CHAR(10),
    P_RETAILPRICE DECIMAL(10,2),
    P_COMMENT VARCHAR(23)
) ENGINE=InnoDB;

-- 创建SUPPLIER表（供应商表）
DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER (
    S_SUPPKEY INT PRIMARY KEY,
    S_NAME CHAR(25),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY INT,
    S_PHONE CHAR(15),
    S_ACCTBAL DECIMAL(10,2),
    S_COMMENT VARCHAR(101),
    FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
) ENGINE=InnoDB;

-- 创建PARTSUPP表（零件供应商表）
DROP TABLE IF EXISTS PARTSUPP;
CREATE TABLE PARTSUPP (
    PS_PARTKEY INT,
    PS_SUPPKEY INT,
    PS_AVAILQTY INT,
    PS_SUPPLYCOST DECIMAL(10,2),
    PS_COMMENT VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
    FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
) ENGINE=InnoDB;

-- 创建CUSTOMER表（客户表）
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    C_CUSTKEY INT PRIMARY KEY,
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY INT,
    C_PHONE CHAR(15),
    C_ACCTBAL DECIMAL(10,2),
    C_MKTSEGMENT CHAR(10),
    C_COMMENT VARCHAR(117),
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
) ENGINE=InnoDB;

-- 创建ORDERS表（订单表）
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
    O_ORDERKEY INT PRIMARY KEY,
    O_CUSTKEY INT,
    O_ORDERSTATUS CHAR(1),
    O_TOTALPRICE DECIMAL(10,2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK CHAR(15),
    O_SHIPPRIORITY INT,
    O_COMMENT VARCHAR(79),
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
) ENGINE=InnoDB;

-- 创建LINEITEM表（订单明细表）
DROP TABLE IF EXISTS LINEITEM;
CREATE TABLE LINEITEM (
    L_ORDERKEY INT,
    L_PARTKEY INT,
    L_SUPPKEY INT,
    L_LINENUMBER INT,
    L_QUANTITY DECIMAL(10,2),
    L_EXTENDEDPRICE DECIMAL(10,2),
    L_DISCOUNT FLOAT,
    L_TAX FLOAT,
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY),
    FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY)
) ENGINE=InnoDB;

-- 显示创建的表
SHOW TABLES;

-- 显示表结构信息
SELECT 
    TABLE_NAME as 'Table',
    TABLE_ROWS as 'Estimated Rows',
    ROUND(DATA_LENGTH/1024/1024, 2) as 'Data Size (MB)',
    ROUND(INDEX_LENGTH/1024/1024, 2) as 'Index Size (MB)'
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = 'TPC_H'
ORDER BY TABLE_NAME;
